[package]
name = "rust_game"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]

[features]

[dependencies]
winit = "0.18.*"
vulkano = "0.11.*"
vulkano-shaders = "0.11.*"
vulkano-win = "0.11.*"
image = "0.21.*"
lazy_static = "1.2.*"
